### ISSUE TITLE
fuck you ,i love china!!!!

### ISSUE THREAD

**Issue by END66** [gfw-breaker/nogfw#6]
fuck you ,i love china!!!!
fuck you ,i love china!!!!
fuck you ,i love china!!!!
fuck you ,i love china!!!!

**Comment by END66** [comment]
good night



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "翻墙教练"<notifications@github.com&gt;; 
发送时间: 2019年12月17日(星期二) 晚上6:16
收件人: "gfw-breaker/nogfw"<nogfw@noreply.github.com&gt;; 
抄送: "END"<1791766039@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [gfw-breaker/nogfw] fuck you ,i love china!!!! (#6)




Closed #6.

**Comment by Robertxzx** [comment]
fuck you，chinazi !!
